version: '3.8'

services:
  shareit-db:
    image: postgres:16.1
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shareit" ]
      interval: 5s
      timeout: 5s
      retries: 5

  shareit-server:
    build:
      context: ./shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shareit-db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      shareit-db:
        condition: service_healthy

  shareit-gateway:
    build:
      context: ./shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090
    depends_on:
      - shareit-server
